WhoWantsToBeAMillionaireGame/Areas/AdminGame/Controllers/AdvertisingController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WhoWantsToBeAMillionaireGame.Core.Abstractions;
using WhoWantsToBeAMillionaireGame.Core.DataTransferObjects;
using WhoWantsToBeAMillionaireGame.Models.Admin.AdvertiseModels;

namespace WhoWantsToBeAMillionaireGame.Areas.AdminGame.Controllers
{
    [Authorize]
    [Area("AdminGame")]
    public class AdvertisingController : Controller
    {
        public IAdvertiseService _advertiseService { get; }
        private readonly IWebHostEnvironment _environment;
        private readonly ISocialMediaLinkService _socialMediaLinkService;
        public IMapper Mapper { get; }

        public AdvertisingController(IAdvertiseService advertiseService, IMapper mapper, IWebHostEnvironment environment, ISocialMediaLinkService socialMediaLinkService)
        {
            _advertiseService = advertiseService;
            Mapper = mapper;
            _environment = environment;
            _socialMediaLinkService = socialMediaLinkService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> LoadGridData()
        {
            var advertises = await _advertiseService.GetAllAdvertisesAsync();
            return Json(advertises.Where(x => x.IsActive == true));
        }
        [HttpPost]
        public async Task<IActionResult> CreateAdvertise(IFormFile file, [FromForm] AdvertisePostModel data)
        {
            try
            {
                if (file == null || file.Length == 0)
                {
                    return BadRequest("File is not selected or empty.");
                }

                if (!file.ContentType.StartsWith("image/"))
                {
                    return BadRequest("Invalid file type.");
                }

                string uploadsFolder = Path.Combine("uploads");
                Directory.CreateDirectory(uploadsFolder);
                string uniqueFileName = $"{Guid.NewGuid()}_{file.FileName}";
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await file.CopyToAsync(fileStream);
                }
                var dto = Mapper.Map<AdvertiseDto>(data);
                dto.Id = Guid.NewGuid();
                dto.ImageUrl = Path.Combine("uploads", uniqueFileName);
                dto.AdType = string.Empty;
                dto.AdSize = string.Empty;
                dto.CreatedDate = DateTime.UtcNow;
                dto.ModifiedDate = DateTime.MinValue;
                dto.AdPlacement = string.Empty;
                dto.IsActive = true;
                dto.AdStatus = false;

                var response = await _advertiseService.CreateAdvertiseAsync(dto);
                return Json("success");
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"An error occurred: {ex.Message}");
            }
        }

        [HttpPost]
        public async Task<IActionResult> ActivateAdvertise([FromQuery] Guid Id)
        {
            var allAdvertises = await _advertiseService.GetAllAdvertisesAsync();
            if (allAdvertises.Any(x => x.AdStatus == true)) return Json("alreadyActive");
            var advertise = await _advertiseService.GetAdvertiseByIdAsync(Id);
            advertise.AdStatus = true;
            await _advertiseService.UpdateAdvertiseAsync(advertise);
            return Json("success");
        }
        [HttpPost]
        public async Task<IActionResult> DeactiveAdvertise([FromQuery] Guid Id)
        {
            var advertise = await _advertiseService.GetAdvertiseByIdAsync(Id);
            if (advertise.AdStatus == true)
            {
                advertise.AdStatus = false;
                await _advertiseService.UpdateAdvertiseAsync(advertise);
                return Json("success");
            }
            return Json("already");

        }
        [HttpDelete]
        public async Task<IActionResult> DeleteAdvertise([FromQuery] Guid Id)
        {
            var advertise = await _advertiseService.GetAdvertiseByIdAsync(Id);
            if (advertise != null)
            {
                await _advertiseService.DeleteAdvertiseAsync(Id);
                return Json("success");
            }
            return Json("notFound");
        }
        [HttpGet]
        public async Task<IActionResult> GetAdvertisementDetails([FromQuery] Guid Id)
        {
            if (Id != Guid.Empty)
            {
                var advertise = await _advertiseService.GetAdvertiseByIdAsync(Id);
                return Json(advertise);
            }

            return Json("notFound");
        }

        [HttpPost]
        public async Task<IActionResult> SaveSocialMediaLinks([FromForm] SocialMediaLinkDto socialMediaLinkDto)
        {
            if (socialMediaLinkDto != null)
            {
                var entity = await _socialMediaLinkService.GetSocialMediaLink();
                entity.FacebookUrl = socialMediaLinkDto.FacebookUrl;
                entity.TikTokUrl = socialMediaLinkDto.TikTokUrl;
                entity.InstagramUrl = socialMediaLinkDto.InstagramUrl;
                await _socialMediaLinkService.UpdateSocialMediaLink(entity);
                return Json("OK");
            }
            return Json("notFound");
        }

    }
}

WhoWantsToBeAMillionaireGame/Areas/AdminGame/Controllers/UserController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using WhoWantsToBeAMillionaireGame.Business.ServicesImplementations;
using WhoWantsToBeAMillionaireGame.Core.Abstractions;
using WhoWantsToBeAMillionaireGame.Core.DataTransferObjects;
using WhoWantsToBeAMillionaireGame.Models;
using WhoWantsToBeAMillionaireGame.Models.Admin;

namespace WhoWantsToBeAMillionaireGame.Areas.AdminGame.Controllers
{
    [Authorize]
    [Route("Admin/[controller]/[action]")]
    [Area("AdminGame")]
    public class UserController : Controller
    {
        public ILoginUserService _userService { get; }
        public IMapper Mapper { get; }

        public UserController(ILoginUserService userService, IMapper mapper)
        {
            _userService = userService;
            Mapper = mapper;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateUser([FromBody] LoginUserPostModel data)
        {
            var allUsers = await _userService.GetAllUsersAsync();
            if (allUsers.Select(x => x.Email).Contains(data.Email)) return Json("already have");

            var dto = Mapper.Map<LoginUserDto>(data);
            var response = await _userService.CreateUserAsync(dto);
            return Json("success");
        }
        [HttpGet]
        public async Task<IActionResult> LoadGrid()
        {
            var allUsers = await _userService.GetAllUsersAsync();
            return Ok(allUsers);
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteUser(Guid id)
        {
            await _userService.DeleteUserAsync(id);
            return Json("ok");
        }
        [HttpPost]
        public async Task<IActionResult> UpdateUser([FromBody] LoginUserUpdateModel data)
        {
            var allUsers = await _userService.GetAllUsersAsync();
            if (data.Id != null)
            {
                var dto = Mapper.Map<LoginUserDto>(data);
                var response = await _userService.UpdateUserAsync(dto);
                return Json("ok");
            }
            return Json("notok");
        }
        [HttpGet("{id}")]
        public async Task<IActionResult> GetUser(Guid id)
        {
            if (id != null)
            {
                var user = await _userService.GetUserById(id);
                return Json(user);
            }
            return Json("nonUser");
        }
    }
}

WhoWantsToBeAMillionaireGame/Areas/AdminGame/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en" ng-app="yourApp">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Admin Panel</title>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/admin/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/admin/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="~/placement/placement.css">
    <link href="~/css/spinner.css" rel="stylesheet" />
    <link href=" https://cdn.jsdelivr.net/npm/sweetalert2@11.7.3/dist/sweetalert2.min.css " rel="stylesheet">



    <script src="~/admin/plugins/jquery/jquery.min.js"></script>
    <script src="~/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.8.3/angular.min.js" integrity="sha512-KZmyTq3PLx9EZl0RHShHQuXtrvdJ+m35tuOiwlcZfs/rE7NZv29ygNA8SFCkMXTnYZQK2OX0Gm2qKGfvWEtRXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/Script/layout.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4"></script>
    <script src="https://cdn.jsdelivr.net/npm/angular-chart.js@1.1.1"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11.3.0/dist/sweetalert2.min.js"></script>

    <script asp-append-version="true" src="~/Script/app.js"></script>

</head>

<body class="hold-transition sidebar-mini">

    <div class="wrapper">
        <div id="spinner-container" class="spinner" ng-style="{'display': showSpinner ? 'block' : 'none'}"></div>

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Navbar Search -->
                <!-- Messages Dropdown Menu -->
                <!-- Notifications Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-bell"></i>
                        <span class="badge badge-warning navbar-badge">15</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-header">15 Notifications</span>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-envelope mr-2"></i> 4 new messages
                            <span class="float-right text-muted text-sm">3 mins</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-users mr-2"></i> 8 friend requests
                            <span class="float-right text-muted text-sm">12 hours</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-file mr-2"></i> 3 new reports
                            <span class="float-right text-muted text-sm">2 days</span>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-widget="fullscreen" href="#" role="button">
                        <i class="fas fa-expand-arrows-alt"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                        <i class="fas fa-th-large"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="#" class="brand-link">
                <img src="~/admin/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">Oyna və Qazan </span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="info">
                        <a href="#" class="d-block">Admin</a>
                    </div>
                </div>

                <!-- SidebarSearch Form -->
                <!-- Sidebar Menu -->
                <nav id="admin-nav" class="mt-2">
                    <ul id="admin-nav" class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                             with font-awesome or any other icon font library -->
                        <li class="nav-item menu-open">
                            <a href="#" class="nav-link active">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Alətlər
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Question" asp-area="AdminGame" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Suallar</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Prize" asp-area="AdminGame" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Hədiyyələr</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="Advertising" asp-area="AdminGame" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Reklam yerləşdirmək</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-action="Index" asp-controller="User" asp-area="AdminGame" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>İstifadəçilər</p>
                                    </a>
                                </li>
                            </ul>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <!-- Default to the left -->
            <strong>Copyright &copy; 2023 </strong>
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    @RenderSection("Scripts", required: false)
    <script src="~/admin/dist/js/adminlte.min.js"></script>
</body>
</html>